' FreeBASIC (-lang qb) declarations of the C side: ALPCLIB.C (port/alpclib.h)
' and the web console (port/fb/console.c). Same names as port/lib.bi.
DECLARE SUB rv_setpag2 CDECL ALIAS "rv_setpag2" (p AS INTEGER)
DECLARE FUNCTION rv_pag2get CDECL ALIAS "rv_pag2get" (BYVAL x AS INTEGER, BYVAL y AS INTEGER) AS INTEGER
DECLARE SUB rv_dump CDECL ALIAS "rv_dumpfb" (BYVAL path AS STRING)
DECLARE FUNCTION rv_visible CDECL ALIAS "rv_visible" () AS INTEGER
DECLARE SUB rv_wait CDECL ALIAS "rv_wait" (BYVAL ms AS INTEGER)
DECLARE FUNCTION rv_mousein CDECL ALIAS "rv_mousein" () AS INTEGER
DECLARE FUNCTION rv_mx CDECL ALIAS "rv_mx" () AS INTEGER
DECLARE FUNCTION rv_my CDECL ALIAS "rv_my" () AS INTEGER
DECLARE FUNCTION rv_mb CDECL ALIAS "rv_mb" () AS INTEGER
DECLARE SUB ccls CDECL ALIAS "ccls" (BYVAL pag AS INTEGER)
DECLARE SUB ClearRight CDECL ALIAS "clearright" (BYVAL pag AS INTEGER)
DECLARE SUB Box CDECL ALIAS "box" (BYVAL lc AS INTEGER, BYVAL rc AS INTEGER, BYVAL tc AS INTEGER, BYVAL bc AS INTEGER, BYVAL nl AS INTEGER, BYVAL fclr AS INTEGER, BYVAL pag AS INTEGER)
DECLARE SUB cPutSym CDECL ALIAS "cputsym" (BYVAL sym AS INTEGER, BYVAL x AS INTEGER, BYVAL y AS INTEGER, BYVAL fc AS INTEGER, BYVAL bc AS INTEGER, BYVAL pag AS INTEGER)
DECLARE FUNCTION cGetSym CDECL ALIAS "cgetsym" (BYVAL x AS INTEGER, BYVAL y AS INTEGER, BYVAL pag AS INTEGER) AS INTEGER
DECLARE SUB cRandomize CDECL ALIAS "crandomize" (BYVAL seed AS SINGLE)
DECLARE FUNCTION Confuse CDECL ALIAS "confuse" (BYVAL r AS INTEGER, BYVAL i AS INTEGER) AS INTEGER
DECLARE FUNCTION RollDice CDECL ALIAS "rolldice" (BYVAL dsize AS INTEGER, BYVAL nroll AS INTEGER, BYVAL nuse AS INTEGER) AS INTEGER
DECLARE FUNCTION cRd CDECL ALIAS "crd" (BYVAL x AS INTEGER, BYVAL y AS INTEGER) AS INTEGER
DECLARE FUNCTION cRdSimp CDECL ALIAS "crdsimp" (BYVAL x AS INTEGER, BYVAL y AS INTEGER) AS INTEGER
DECLARE FUNCTION cRoll CDECL ALIAS "croll" (BYVAL max AS INTEGER) AS INTEGER
DECLARE FUNCTION cFindDxDy CDECL ALIAS "cfinddxdy" (BYVAL x AS INTEGER, BYVAL y AS INTEGER, BYVAL n AS INTEGER) AS INTEGER
DECLARE FUNCTION RoomIt CDECL ALIAS "roomit" (BYVAL xr AS INTEGER, BYVAL xl AS INTEGER, BYVAL yb AS INTEGER, BYVAL yt AS INTEGER) AS INTEGER
DECLARE SUB Lair CDECL ALIAS "lair" (xr AS INTEGER, xl AS INTEGER, yb AS INTEGER, yt AS INTEGER, xs AS INTEGER, ys AS INTEGER)
DECLARE SUB FindDot CDECL ALIAS "finddot" (x AS INTEGER, y AS INTEGER, BYVAL i AS INTEGER)
DECLARE SUB cMainMap CDECL ALIAS "cmainmap" (BYVAL irnd AS INTEGER, BYVAL jrnd AS INTEGER)
DECLARE SUB cDetailedMap CDECL ALIAS "cdetailedmap" (BYVAL t AS INTEGER, BYVAL t1 AS INTEGER, BYVAL t2 AS INTEGER, BYVAL t3 AS INTEGER, BYVAL t4 AS INTEGER)
DECLARE SUB CreatSort CDECL ALIAS "creatsort" (BYVAL nnear AS INTEGER, tentgrab AS INTEGER, nn AS INTEGER)
DECLARE FUNCTION cSameRoom CDECL ALIAS "csameroom" (BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER, BYVAL lx AS INTEGER, BYVAL ly AS INTEGER, BYVAL n AS INTEGER, nn AS INTEGER) AS INTEGER
DECLARE FUNCTION BadMoveCreat CDECL ALIAS "badmovecreat" (BYVAL dx AS INTEGER, BYVAL dy AS INTEGER, BYVAL n AS INTEGER, BYVAL c AS INTEGER, nn AS INTEGER) AS INTEGER
DECLARE SUB rv_beacon CDECL ALIAS "rv_beacon" (BYVAL spec AS INTEGER, BYVAL killer AS STRING, BYVAL who AS STRING, BYVAL depth AS INTEGER, BYVAL score AS LONG, BYVAL lvl AS INTEGER)
