#!/usr/bin/env python3
"""Merge the QuickBasic 4.5 modules A1..A8 into one source.

QB64 has no multi-module linking, so: library block + DEFINT + includes once,
A1's module code, the other modules' module-level DIM/DATA, then every SUB/FUNCTION.
  merge.py     -> port/alphaman.bas    (QB64-PE, native; port/build.sh)
  merge.py fb  -> port/fb/alphaman.bas (FreeBASIC -lang qb, web; web/build.sh)
The fb output inlines lib.bm/rvip.bm, keeps the DECLAREs (FreeBASIC needs
them) and swaps the few QB64-only statements for the C console's functions.
"""
import re, sys, pathlib

fb = len(sys.argv) > 1 and sys.argv[1] == "fb"
root = pathlib.Path(__file__).resolve().parent.parent
rd = lambda n: (root / n).read_text(encoding="latin-1").replace("\r\n", "\n").split("\n")

sub_start = re.compile(r"^\s*(STATIC\s+)?(SUB|FUNCTION)\s", re.I)
sub_end = re.compile(r"^\s*END\s+(SUB|FUNCTION)\b", re.I)
skip = re.compile(r"^\s*(DEFINT\s|REM \$INCLUDE)" + ("" if fb else r"|^\s*DECLARE\s"), re.I)
dos = re.compile(r"DEF SEG = 0: POKE \(&H417\).*?DEF SEG = &HB800", re.I)

# keyboard input goes through rv_key$ / rv_line$ (port/lib.bm)
fixes = [("WHILE st1 = \"\": st1 = INKEY$: WEND", "st1 = rv_key$"),
         ("INPUT \" \", Comm$", "PRINT \" \";: Comm$ = rv_line$"),
]
fb_fixes = [(r"CLEAR , , 10000: ", ""), (r"Comm\$ = COMMAND\$", "Comm$ = ENVIRON$(\"ALPHA_NAME\")"),   # argv is empty under Asyncify; JS sets ALPHA_NAME
            (r"\b_LIMIT 100\b", "rv_wait 10"), (r"\b_LIMIT 60\b", "rv_wait 16"),
            (r"\b_MOUSEINPUT\b", "rv_mousein"), (r"\b_MOUSEBUTTON\(1\)", "rv_mb"), (r"\b_MOUSEX\b", "rv_mx"), (r"\b_MOUSEY\b", "rv_my")]
main, extra, subs, decl, declared = [], [], [], [], set()
c_names = {m.lower() for m in re.findall(r"^DECLARE (?:SUB|FUNCTION) (\w+)", (root / "port/fb/lib.bi").read_text(), re.M)} if fb else set()
for n in range(1, 9):
    ins = False
    for line in rd(f"A{n}.BAS.txt"):
        for a, b in fixes:
            line = line.replace(a, b)
        line = re.sub(r"LINE INPUT ; *(\w+\$?)", r"\1 = rv_line$", line)
        line = re.sub(r'INPUT (?:; )?("[^"]*"), (\w+\$|st1\b)', r"PRINT \1;: \2 = rv_line$", line)
        line = re.sub(r'INPUT (?:; )?("[^"]*"), (\w+)\b', r"PRINT \1;: \2 = VAL(rv_line$)", line)
        line = dos.sub("REM numlock poke removed", line)
        line = re.sub(r"DEF SEG = &HB800:\s*", "", line, flags=re.I)
        if fb:
            for a, b in fb_fixes:
                line = re.sub(a, b, line)
        if sub_start.match(line):
            ins = True
        if ins:
            subs.append(line)
            if sub_end.match(line):
                ins = False
                subs.append("")
            continue
        if skip.match(line):
            continue
        if line.upper().lstrip().startswith("DECLARE "):
            # one per name (parameter names differ between modules); the C
            # ones are in port/fb/lib.bi; SEG (far pointer) is plain BYREF here
            name = re.match(r"DECLARE (?:SUB|FUNCTION) (\w+)", line.strip(), re.I).group(1).lower()
            if name not in declared and name not in c_names:
                declared.add(name)
                decl.append(line.strip().replace("SEG ", ""))
            continue
        if n == 1:
            main.append(line)
        elif line.strip() and line.strip().upper() != "END" and not line.lstrip().startswith("'"):
            extra.append(line)

def rv_lines(name):
    """lib.bm / rvip.bm for the fb output, with their DECLAREs."""
    out = []
    for l in rd(name):
        for a, b in fb_fixes:
            l = re.sub(a, b, l)
        m = re.match(r"^(SUB|FUNCTION)\s+(\S+)\s*(\(.*\))?", l)
        if m:
            decl.append(f"DECLARE {m.group(1)} {m.group(2)} {m.group(3) or '()'}")
        out.append(l)
    return out

out = ["' Generated by port/merge.py from A1..A8.BAS.txt -- edit the sources, not this file."]
if fb:
    rv = rv_lines("port/fb/lib.bm") + rv_lines("port/rvip.bm")
    out += ["#include \"lib.bi\"", "DEFINT A-Z"] + decl
else:
    out += ["$RESIZE:STRETCH", "'$INCLUDE: 'lib.bi'", "DEFINT A-Z"]
# QB64: arrays DIMmed and then named in COMMON SHARED are not shared, so
# DIM SHARED them and drop the array entries from COMMON SHARED.
dec = []
for l in rd("ALPHA.DEC"):
    if l.upper().startswith("DIM "):
        l = "DIM SHARED " + l[4:]
    elif l.upper().startswith("COMMON SHARED "):
        names = [v for v in l[14:].split(",") if "()" not in v]
        if not names:
            continue
        l = "COMMON SHARED " + ",".join(names)
    dec.append(l)
out += rd("ALPHA.DC2") + dec
# creature record of file #3 (LEN = 50), was FIELD nm$/dud$ (A7 CreatNam$, Creature)
out += ["TYPE rv_creat", "  nm AS STRING * 20", "  dud AS STRING * 30", "END TYPE", "DIM SHARED rv_cr AS rv_creat"]
out += [l for l in extra if l.upper().lstrip().startswith("DIM")]
out += ["#include \"init.bi\"" if fb else "'$INCLUDE: 'init.bi'"]
out += main
out += ["END", ""] + [l for l in extra if not l.upper().lstrip().startswith("DIM")]
out += [""] + subs
if fb:
    out += rv
    (root / "port" / "fb" / "alphaman.bas").write_text("\n".join(out) + "\n", encoding="latin-1")
else:
    out += ["'$INCLUDE: 'lib.bm'", "'$INCLUDE: 'rvip.bm'"]
    (root / "port" / "alphaman.bas").write_text("\n".join(out) + "\n", encoding="latin-1")
