#!/usr/bin/env python3
"""Merge the QuickBasic 4.5 modules A1..A8 into one QB64 source (port/alphaman.bas).

QB64 has no multi-module linking, so: library block + DEFINT + includes once,
A1's module code, the other modules' module-level DIM/DATA, then every SUB/FUNCTION.
"""
import re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
rd = lambda n: (root / n).read_text(encoding="latin-1").replace("\r\n", "\n").split("\n")

sub_start = re.compile(r"^\s*(STATIC\s+)?(SUB|FUNCTION)\s", re.I)
sub_end = re.compile(r"^\s*END\s+(SUB|FUNCTION)\b", re.I)
skip = re.compile(r"^\s*(DECLARE\s|DEFINT\s|REM \$INCLUDE)", re.I)
dos = re.compile(r"DEF SEG = 0: POKE \(&H417\).*?DEF SEG = &HB800", re.I)

# keyboard input goes through rv_key$ / rv_line$ (port/lib.bm)
fixes = [("WHILE st1 = \"\": st1 = INKEY$: WEND", "st1 = rv_key$"),
         ("INPUT \" \", Comm$", "PRINT \" \";: Comm$ = rv_line$"),
]
main, extra, subs = [], [], []
for n in range(1, 9):
    ins = False
    for line in rd(f"A{n}.BAS.txt"):
        for a, b in fixes:
            line = line.replace(a, b)
        line = re.sub(r"LINE INPUT ; *(\w+\$?)", r"\1 = rv_line$", line)
        line = re.sub(r'INPUT (?:; )?("[^"]*"), (\w+\$|st1\b)', r"PRINT \1;: \2 = rv_line$", line)
        line = re.sub(r'INPUT (?:; )?("[^"]*"), (\w+)\b', r"PRINT \1;: \2 = VAL(rv_line$)", line)
        if sub_start.match(line):
            ins = True
        if ins:
            subs.append(line)
            if sub_end.match(line):
                ins = False
                subs.append("")
            continue
        if skip.match(line):
            continue
        line = dos.sub("REM numlock poke removed", line)
        line = re.sub(r"DEF SEG = &HB800:\s*", "", line, flags=re.I)
        if n == 1:
            main.append(line)
        elif line.strip() and line.strip().upper() != "END" and not line.lstrip().startswith("'"):
            extra.append(line)

out = ["' Generated by port/merge.py from A1..A8.BAS.txt -- edit the sources, not this file.",
       "$RESIZE:STRETCH", "'$INCLUDE: 'lib.bi'", "DEFINT A-Z"]
# QB64: arrays DIMmed and then named in COMMON SHARED are not shared, so
# DIM SHARED them and drop the array entries from COMMON SHARED.
dec = []
for l in rd("ALPHA.DEC"):
    if l.upper().startswith("DIM "):
        l = "DIM SHARED " + l[4:]
    elif l.upper().startswith("COMMON SHARED "):
        names = [v for v in l[14:].split(",") if "()" not in v]
        if not names:
            continue
        l = "COMMON SHARED " + ",".join(names)
    dec.append(l)
out += rd("ALPHA.DC2") + dec
out += [l for l in extra if l.upper().lstrip().startswith("DIM")]
out += ["'$INCLUDE: 'init.bi'"]
out += main
out += ["END", ""] + [l for l in extra if not l.upper().lstrip().startswith("DIM")]
out += [""] + subs + ["'$INCLUDE: 'lib.bm'", "'$INCLUDE: 'rvip.bm'"]
(root / "port" / "alphaman.bas").write_text("\n".join(out) + "\n", encoding="latin-1")
